name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs: 

  build:

    runs-on: ubuntu-latest
    if: github.repository_owner == 'alshedivat'

    steps:
    - name: Checkout
<<<<<<< HEAD
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login
      uses: docker/login-action@v2
=======
      uses: actions/checkout@v2
    - name: Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login
      uses: docker/login-action@v1
>>>>>>> 320fd374 (Initial commit)
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
         
    - name: Build and push
<<<<<<< HEAD
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64/v8
=======
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
>>>>>>> 320fd374 (Initial commit)
        tags: amirpourmand/al-folio
