name: Docker Image CI (Upload Tag)

on:
  push:
    tags:
      - 'v*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
<<<<<<< HEAD
      uses: actions/checkout@v3
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2 
      
    - name: Buildx
      uses: docker/setup-buildx-action@v2
      
=======
      uses: actions/checkout@v2
    - name: Buildx
      uses: docker/setup-buildx-action@v1

>>>>>>> 320fd374 (Initial commit)
    -
      name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: amirpourmand/al-folio

    - name: Login
<<<<<<< HEAD
      uses: docker/login-action@v2
=======
      uses: docker/login-action@v1
>>>>>>> 320fd374 (Initial commit)
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
<<<<<<< HEAD
        platforms: linux/amd64,linux/arm64/v8
=======
>>>>>>> 320fd374 (Initial commit)
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

